/**
 * MODULE 6 — PUBLISHER
 * Saves processed video metadata to DB and marks queue item as done.
 * Generates unique SEO slugs from titles.
 */

const { PrismaClient } = require('@prisma/client');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const prisma = new PrismaClient();

/**
 * Generate a URL-safe slug from a title with a short random suffix
 * e.g. "Hot Desi Girl Dance" → "hot-desi-girl-dance-a3f9"
 */
function generateSlug(title) {
  const base = title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .substring(0, 60);

  const suffix = Math.random().toString(36).substring(2, 6);
  return `${base}-${suffix}`;
}

/**
 * Auto-generate SEO description (300-500 words) if user skipped it.
 * Uses title, category, and tags to produce unique content.
 */
function autoGenerateDescription(title, category, tags) {
  const tagList = tags.length > 0 ? tags.join(', ') : 'desi, indian';
  const cat = category || 'desi';

  const templates = [
    `Watch ${title} — an exciting ${cat} video that captures the best of Indian entertainment. This video has been carefully curated for viewers who enjoy authentic desi content. The clip features high-energy performance and stunning visuals that make it stand out from ordinary ${cat} videos online.

If you enjoy ${tagList} content, this is exactly what you have been searching for. The video showcases real talent and passionate performance that is hard to find elsewhere. Every second of this clip has been recorded with care, ensuring the viewer gets the best possible experience.

Indian content has exploded in popularity worldwide, and videos tagged with ${tagList} consistently rank among the most searched categories. This particular video brings together elements that fans of ${cat} content love — raw energy, natural performance, and authentic Indian flavor.

Whether you are new to ${cat} content or a long-time fan, this video will not disappoint. The ${title} clip is one of many premium desi videos available on our platform. Browse our extensive collection of ${tagList} videos and discover new favorites every day.

Our platform is dedicated to bringing you the finest desi entertainment collection. Every video is processed for smooth playback, fast loading, and the best viewing experience on both mobile and desktop. We update our library regularly so you always have fresh content to enjoy.

Explore related videos, browse by category, or search by tags to find more content like ${title}. Our recommendation engine ensures you always find videos that match your taste. Save your favorites, share with friends, and come back daily for new uploads.`,

    `${title} is one of the most popular videos in our ${cat} collection. Fans of ${tagList} content will immediately recognize why this video has captured so much attention. The clip is authentic, energetic, and delivers exactly what desi content lovers are looking for.

This video is part of our growing library of ${cat} content from across India. We work hard to source and curate only the best videos so that our users get top-quality entertainment every time they visit. The ${title} video is a perfect example of the standard we uphold.

Indian entertainment is diverse, vibrant, and full of passion — qualities that are clearly visible in this ${cat} video. Videos featuring ${tagList} themes have always performed strongly, and this particular clip continues that tradition with style and confidence.

Our platform hosts thousands of similar videos, all tagged and categorized for easy discovery. If you loved ${title}, you will find our related videos section especially useful. We feature similar clips ranked by popularity, recency, and viewer engagement.

We are committed to providing a fast, ad-light, mobile-friendly experience. All our videos are encoded for quick streaming and include thumbnails for easy browsing. Our dedication to performance means you spend less time buffering and more time enjoying great ${cat} content.

Bookmark this page, explore our tag pages, and check out our category sections for more videos like ${title}. New content is added regularly, so there is always something fresh waiting for you in our ${tagList} collection.`,
  ];

  return templates[Math.floor(Math.random() * templates.length)];
}

/**
 * Publish a video to the database
 * @param {object} opts
 * @param {string} opts.title
 * @param {string} opts.description - can be empty (auto-generated)
 * @param {string} opts.filePath - relative web path e.g. /videos/001/000001.mp4
 * @param {string} opts.thumbnail - relative web path e.g. /videos/001/000001.jpg
 * @param {string} opts.category
 * @param {string[]} opts.tags
 * @param {string} opts.cdnUrl - original queue URL to mark as done
 */
async function publishVideo({ title, description, filePath, thumbnail, category, tags, cdnUrl }) {
  // Auto-generate description if empty
  const finalDesc = description && description.trim().length > 50
    ? description.trim()
    : autoGenerateDescription(title, category, tags);

  // Generate unique slug
  let slug = generateSlug(title);

  // Ensure slug uniqueness (retry up to 5 times)
  for (let i = 0; i < 5; i++) {
    const existing = await prisma.video.findUnique({ where: { slug } });
    if (!existing) break;
    slug = generateSlug(title); // regenerate with new suffix
  }

  const video = await prisma.video.create({
    data: {
      title: title.trim(),
      slug,
      filePath,
      thumbnail,
      description: finalDesc,
      category: category || 'desi',
      tags: tags.length > 0 ? tags : ['desi', 'indian'],
      views: 0,
    },
  });

  // Mark queue item as done
  if (cdnUrl) {
    await prisma.videoQueue.update({
      where: { cdnUrl },
      data: { status: 'done' },
    });
  }

  console.log(`\n  ✅ Published: "${video.title}"`);
  console.log(`     Slug:      ${video.slug}`);
  console.log(`     URL:       ${process.env.NEXT_PUBLIC_APP_URL || 'https://ilovedesi.fun'}/video/${video.slug}`);

  return video;
}

module.exports = { publishVideo, generateSlug, autoGenerateDescription };

// Allow running standalone for testing
if (require.main === module) {
  publishVideo({
    title: 'Test Desi Video',
    description: '',
    filePath: '/videos/001/000001.mp4',
    thumbnail: '/videos/001/000001.jpg',
    category: 'desi',
    tags: ['desi', 'indian', 'test'],
    cdnUrl: null,
  })
    .then(() => prisma.$disconnect())
    .catch(e => { console.error(e); prisma.$disconnect(); process.exit(1); });
}
