'use server'

import { revalidatePath } from 'next/cache'
import { PrismaClient } from '@prisma/client'
import { spawnSync } from 'child_process'
import path from 'path'
import fs from 'fs'
import os from 'os'
import crypto from 'crypto'

const prisma = new PrismaClient()
const DATA_DIR = process.env.DATA_DIR || '/root/vidpipe/data/videos'

// 1. Storage Helpers
function getBatch(id: number) {
  return String(Math.floor((id - 1) / 1000) + 1).padStart(3, '0')
}

function getVideoPath(id: number) {
  const batch = getBatch(id)
  const paddedId = String(id).padStart(6, '0')
  const dir = path.join(DATA_DIR, batch)
  return {
    dir,
    videoPath: path.join(dir, `${paddedId}.mp4`),
    thumbPath: path.join(dir, `${paddedId}.jpg`),
    videoUrl: `/videos/${batch}/${paddedId}.mp4`,
    thumbUrl: `/videos/${batch}/${paddedId}.jpg`,
  }
}

// 2. Processing Helpers
function downloadUrl(url: string, destPath: string) {
  const result = spawnSync('curl', ['-L', '-o', destPath, '--retry', '3', '--max-time', '600', '-s', url])
  if (result.status !== 0 || !fs.existsSync(destPath) || fs.statSync(destPath).size < 10240) {
    throw new Error('Download failed')
  }
}

function processFfmpeg(tmpFile: string, videoPath: string, thumbPath: string, thumbTime: string) {
  // Compress to 240p, preserve aspect ratio (no stretch)
  const cRes = spawnSync('ffmpeg', [
    '-i', tmpFile, '-vf', "scale=-2:240", '-c:v', 'libx264', '-crf', '28',
    '-c:a', 'aac', '-b:a', '64k', '-movflags', '+faststart', '-y', videoPath
  ])
  const compressed = cRes.status === 0

  // Thumbnail
  const targetForThumb = compressed ? videoPath : tmpFile
  const tRes = spawnSync('ffmpeg', [
    '-i', targetForThumb, '-ss', thumbTime, '-vframes', '1', '-q:v', '2', '-y', thumbPath
  ])
  const thumbed = tRes.status === 0

  if (!compressed) fs.copyFileSync(tmpFile, videoPath)
  return thumbed
}

// 3. Publisher
function generateSlug(title: string) {
  const base = title.toLowerCase().replace(/[^a-z0-9\s-]/g, '').trim().replace(/\s+/g, '-').replace(/-+/g, '-').substring(0, 60)
  return `${base}-${crypto.randomBytes(2).toString('hex')}`
}

function autoGenerateDescription(title: string, category: string, tags: string[]) {
  const tagList = tags.length > 0 ? tags.join(', ') : 'desi, indian'
  return `Watch ${title} — an exciting ${category} video that captures the best of Indian entertainment. This video has been carefully curated for viewers who enjoy authentic desi content. The clip features high-energy performance and stunning visuals that make it stand out from ordinary ${category} videos online.

If you enjoy ${tagList} content, this is exactly what you have been searching for. The video showcases real talent and passionate performance that is hard to find elsewhere. Every second of this clip has been recorded with care, ensuring the viewer gets the best possible experience.

Indian content has exploded in popularity worldwide, and videos tagged with ${tagList} consistently rank among the most searched categories. This particular video brings together elements that fans of ${category} content love — raw energy, natural performance, and authentic Indian flavor.`
}

// 4. MAIN ACTION
export async function addAndProcessVideo(formData: FormData) {
  const url = formData.get('url') as string
  const rawTitle = formData.get('title') as string
  const description = formData.get('description') as string
  const category = (formData.get('category') as string) || 'desi'
  const tagsRaw = formData.get('tags') as string
  const thumbTime = (formData.get('thumbTime') as string) || '5'
  const customThumbUrl = formData.get('thumbUrl') as string

  if (!url) return { error: 'URL is required' }

  const urlTitle = path.basename(url).replace(/\.[^.]+$/, '').replace(/[-_]/g, ' ')
  const title = rawTitle || urlTitle.charAt(0).toUpperCase() + urlTitle.slice(1) || 'Desi Video'
  const tags = tagsRaw ? tagsRaw.split(',').map(t => t.trim()).filter(Boolean) : ['desi', 'indian']

  // Queue tracking
  await prisma.videoQueue.upsert({
    where: { cdnUrl: url },
    create: { cdnUrl: url, status: 'processing' },
    update: { status: 'processing' },
  })

  const tmpFile = path.join(os.tmpdir(), `vidpipe_raw_${Date.now()}.mp4`)

  try {
    // 1. Download
    downloadUrl(url, tmpFile)

    // 2. Storage Path
    const latest = await prisma.video.findFirst({ orderBy: { id: 'desc' } })
    const nextId = (latest?.id ?? 0) + 1
    const paths = getVideoPath(nextId)
    fs.mkdirSync(paths.dir, { recursive: true })

    // 3. Size tracking (Original)
    let originalSizeMb = 0
    let compressedSizeMb = 0
    try {
      const stat = fs.statSync(tmpFile)
      originalSizeMb = Number((stat.size / (1024 * 1024)).toFixed(2))
    } catch (e) {}

    // 4. Process
    const thumbed = processFfmpeg(tmpFile, paths.videoPath, paths.thumbPath, thumbTime)

    // 5. Size tracking (Compressed)
    try {
      const stat = fs.statSync(paths.videoPath)
      compressedSizeMb = Number((stat.size / (1024 * 1024)).toFixed(2))
    } catch (e) {}

    // 6. Publish
    let slug = generateSlug(title)
    
    // Fallback description
    const finalDesc = description && description.trim().length > 50 
      ? description.trim() 
      : autoGenerateDescription(title, category, tags)

    // Select thumbnail: custom URL > FFmpeg generated > placeholder
    const finalThumbnail = customThumbUrl ? customThumbUrl : (thumbed ? paths.thumbUrl : '/placeholder.jpg')

    const video = await prisma.video.create({
      data: {
        title,
        slug,
        filePath: paths.videoUrl,
        thumbnail: finalThumbnail,
        description: finalDesc,
        category,
        tags,
        originalSizeMb,
        compressedSizeMb
      }
    })

    // Mark Done
    await prisma.videoQueue.update({ where: { cdnUrl: url }, data: { status: 'done' } })
    try { fs.unlinkSync(tmpFile) } catch {}

    revalidatePath('/')
    revalidatePath('/admin')
    revalidatePath('/admin/queue')

    return { success: true, slug: video.slug }
  } catch (error: any) {
    await prisma.videoQueue.update({ where: { cdnUrl: url }, data: { status: 'failed', retryCount: { increment: 1 } } })
    try { fs.unlinkSync(tmpFile) } catch {}
    return { error: error.message || 'Processing failed' }
  }
}
